/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_znn_ndktransferdata_MainActivity */

#ifndef _Included_com_znn_ndktransferdata_MainActivity
#define _Included_com_znn_ndktransferdata_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_znn_ndktransferdata_MainActivity
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_znn_ndktransferdata_MainActivity_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_znn_ndktransferdata_MainActivity
 * Method:    doString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_znn_ndktransferdata_MainActivity_doString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_znn_ndktransferdata_MainActivity
 * Method:    doArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_znn_ndktransferdata_MainActivity_doArray
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
